TEST_REPOSITORIES = [
    {
        "_id": "user/repo1",
        "data": {
            "full_name": "user/repo1",
            "private": False,
            "language": "Python",
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "pushed_at": "2025-01-01T00:00:00Z",
            "stars_count": 10,
            "watchers_count": 5,
            "forks_count": 2,
            "issue_count": 1,
            "pull_request_count": 0,
            "workflows_count": 1,
            "url": "https://github.com/user/repo1"
        }
    },
    {
        "_id": "user/repo2",
        "data": {
            "full_name": "user/repo2",
            "private": False,
            "language": "JavaScript",
            "created_at": "2024-02-01T00:00:00Z",
            "updated_at": "2025-02-01T00:00:00Z",
            "pushed_at": "2025-02-01T00:00:00Z",
            "stars_count": 20,
            "watchers_count": 10,
            "forks_count": 5,
            "issue_count": 3,
            "pull_request_count": 1,
            "workflows_count": 2,
            "url": "https://github.com/user/repo2"
        }
    },
    {
        "_id": "user/repo3",
        "data": {
            "full_name": "user/repo3",
            "private": True,
            "language": "Python",
            "created_at": "2024-03-01T00:00:00Z",
            "updated_at": "2025-03-01T00:00:00Z",
            "pushed_at": "2025-03-01T00:00:00Z",
            "stars_count": 30,
            "watchers_count": 15,
            "forks_count": 8,
            "issue_count": 5,
            "pull_request_count": 2,
            "workflows_count": 3,
            "url": "https://github.com/user/repo3"
        }
    },
    {
        "_id": "user/repo4",
        "data": {
            "full_name": "user/repo4",
            "private": False,
            "language": "Go",
            "created_at": "2024-04-01T00:00:00Z",
            "updated_at": "2025-04-01T00:00:00Z",
            "pushed_at": "2025-04-01T00:00:00Z",
            "stars_count": 15,
            "watchers_count": 7,
            "forks_count": 4,
            "issue_count": 2,
            "pull_request_count": 1,
            "workflows_count": 1,
            "url": "https://github.com/user/repo4"
        }
    },
    {
        "_id": "user/repo5",
        "data": {
            "full_name": "user/repo5",
            "private": True,
            "language": "Rust",
            "created_at": "2024-05-01T00:00:00Z",
            "updated_at": "2025-05-01T00:00:00Z",
            "pushed_at": "2025-05-01T00:00:00Z",
            "stars_count": 25,
            "watchers_count": 12,
            "forks_count": 6,
            "issue_count": 4,
            "pull_request_count": 2,
            "workflows_count": 2,
            "url": "https://github.com/user/repo5"
        }
    },
    {
        "_id": "user/repo6",
        "data": {
            "full_name": "user/repo6",
            "private": False,
            "language": "Java",
            "created_at": "2024-06-01T00:00:00Z",
            "updated_at": "2025-06-01T00:00:00Z",
            "pushed_at": "2025-06-01T00:00:00Z",
            "stars_count": 40,
            "watchers_count": 18,
            "forks_count": 10,
            "issue_count": 6,
            "pull_request_count": 3,
            "workflows_count": 4,
            "url": "https://github.com/user/repo6"
        }
    },
    {
        "_id": "user/repo7",
        "data": {
            "full_name": "user/repo7",
            "private": True,
            "language": "C++",
            "created_at": "2024-07-01T00:00:00Z",
            "updated_at": "2025-07-01T00:00:00Z",
            "pushed_at": "2025-07-01T00:00:00Z",
            "stars_count": 50,
            "watchers_count": 20,
            "forks_count": 12,
            "issue_count": 7,
            "pull_request_count": 4,
            "workflows_count": 5,
            "url": "https://github.com/user/repo7"
        }
    },
    {
        "_id": "user/repo8",
        "data": {
            "full_name": "user/repo8",
            "private": False,
            "language": "C#",
            "created_at": "2024-08-01T00:00:00Z",
            "updated_at": "2025-08-01T00:00:00Z",
            "pushed_at": "2025-08-01T00:00:00Z",
            "stars_count": 35,
            "watchers_count": 16,
            "forks_count": 9,
            "issue_count": 5,
            "pull_request_count": 2,
            "workflows_count": 3,
            "url": "https://github.com/user/repo8"
        }
    },
    {
        "_id": "user/repo9",
        "data": {
            "full_name": "user/repo9",
            "private": False,
            "language": "Ruby",
            "created_at": "2024-09-01T00:00:00Z",
            "updated_at": "2025-09-01T00:00:00Z",
            "pushed_at": "2025-09-01T00:00:00Z",
            "stars_count": 22,
            "watchers_count": 9,
            "forks_count": 5,
            "issue_count": 3,
            "pull_request_count": 1,
            "workflows_count": 1,
            "url": "https://github.com/user/repo9"
        }
    },
    {
        "_id": "user/repo10",
        "data": {
            "full_name": "user/repo10",
            "private": True,
            "language": "TypeScript",
            "created_at": "2024-10-01T00:00:00Z",
            "updated_at": "2025-10-01T00:00:00Z",
            "pushed_at": "2025-10-01T00:00:00Z",
            "stars_count": 28,
            "watchers_count": 11,
            "forks_count": 6,
            "issue_count": 4,
            "pull_request_count": 2,
            "workflows_count": 2,
            "url": "https://github.com/user/repo10"
        }
    },
    {
        "_id": "user/repo11",
        "data": {
            "full_name": "user/repo11",
            "private": False,
            "language": "Kotlin",
            "created_at": "2024-11-01T00:00:00Z",
            "updated_at": "2025-11-01T00:00:00Z",
            "pushed_at": "2025-11-01T00:00:00Z",
            "stars_count": 32,
            "watchers_count": 14,
            "forks_count": 7,
            "issue_count": 5,
            "pull_request_count": 3,
            "workflows_count": 3,
            "url": "https://github.com/user/repo11"
        }
    },
    {
        "_id": "user/repo12",
        "data": {
            "full_name": "user/repo12",
            "private": True,
            "language": "Scala",
            "created_at": "2024-12-01T00:00:00Z",
            "updated_at": "2025-12-01T00:00:00Z",
            "pushed_at": "2025-12-01T00:00:00Z",
            "stars_count": 12,
            "watchers_count": 6,
            "forks_count": 3,
            "issue_count": 2,
            "pull_request_count": 1,
            "workflows_count": 1,
            "url": "https://github.com/user/repo12"
        }
    },
    {
        "_id": "user/repo13",
        "data": {
            "full_name": "user/repo13",
            "private": False,
            "language": "Swift",
            "created_at": "2024-01-15T00:00:00Z",
            "updated_at": "2025-01-15T00:00:00Z",
            "pushed_at": "2025-01-15T00:00:00Z",
            "stars_count": 18,
            "watchers_count": 8,
            "forks_count": 4,
            "issue_count": 2,
            "pull_request_count": 1,
            "workflows_count": 2,
            "url": "https://github.com/user/repo13"
        }
    },
    {
        "_id": "user/repo14",
        "data": {
            "full_name": "user/repo14",
            "private": True,
            "language": "PHP",
            "created_at": "2024-02-15T00:00:00Z",
            "updated_at": "2025-02-15T00:00:00Z",
            "pushed_at": "2025-02-15T00:00:00Z",
            "stars_count": 27,
            "watchers_count": 12,
            "forks_count": 6,
            "issue_count": 3,
            "pull_request_count": 2,
            "workflows_count": 2,
            "url": "https://github.com/user/repo14"
        }
    },
    {
        "_id": "user/repo15",
        "data": {
            "full_name": "user/repo15",
            "private": False,
            "language": "Elixir",
            "created_at": "2024-03-15T00:00:00Z",
            "updated_at": "2025-03-15T00:00:00Z",
            "pushed_at": "2025-03-15T00:00:00Z",
            "stars_count": 21,
            "watchers_count": 9,
            "forks_count": 4,
            "issue_count": 2,
            "pull_request_count": 1,
            "workflows_count": 1,
            "url": "https://github.com/user/repo15"
        }
    },
    {
        "_id": "user/repo16",
        "data": {
            "full_name": "user/repo16",
            "private": True,
            "language": "Perl",
            "created_at": "2024-04-15T00:00:00Z",
            "updated_at": "2025-04-15T00:00:00Z",
            "pushed_at": "2025-04-15T00:00:00Z",
            "stars_count": 14,
            "watchers_count": 6,
            "forks_count": 3,
            "issue_count": 1,
            "pull_request_count": 0,
            "workflows_count": 1,
            "url": "https://github.com/user/repo16"
        }
    },
    {
        "_id": "user/repo17",
        "data": {
            "full_name": "user/repo17",
            "private": False,
            "language": "Haskell",
            "created_at": "2024-05-15T00:00:00Z",
            "updated_at": "2025-05-15T00:00:00Z",
            "pushed_at": "2025-05-15T00:00:00Z",
            "stars_count": 33,
            "watchers_count": 14,
            "forks_count": 7,
            "issue_count": 4,
            "pull_request_count": 2,
            "workflows_count": 2,
            "url": "https://github.com/user/repo17"
        }
    },
    {
        "_id": "user/repo18",
        "data": {
            "full_name": "user/repo18",
            "private": True,
            "language": "Objective-C",
            "created_at": "2024-06-15T00:00:00Z",
            "updated_at": "2025-06-15T00:00:00Z",
            "pushed_at": "2025-06-15T00:00:00Z",
            "stars_count": 19,
            "watchers_count": 8,
            "forks_count": 4,
            "issue_count": 2,
            "pull_request_count": 1,
            "workflows_count": 2,
            "url": "https://github.com/user/repo18"
        }
    },
    {
        "_id": "user/repo19",
        "data": {
            "full_name": "user/repo19",
            "private": False,
            "language": "Shell",
            "created_at": "2024-07-15T00:00:00Z",
            "updated_at": "2025-07-15T00:00:00Z",
            "pushed_at": "2025-07-15T00:00:00Z",
            "stars_count": 24,
            "watchers_count": 10,
            "forks_count": 5,
            "issue_count": 3,
            "pull_request_count": 1,
            "workflows_count": 2,
            "url": "https://github.com/user/repo19"
        }
    },
    {
        "_id": "user/repo20",
        "data": {
            "full_name": "user/repo20",
            "private": True,
            "language": "Dart",
            "created_at": "2024-08-15T00:00:00Z",
            "updated_at": "2025-08-15T00:00:00Z",
            "pushed_at": "2025-08-15T00:00:00Z",
            "stars_count": 26,
            "watchers_count": 11,
            "forks_count": 6,
            "issue_count": 3,
            "pull_request_count": 2,
            "workflows_count": 3,
            "url": "https://github.com/user/repo20"
        }
    }
]

TEST_ISSUES = [
    {
        "_id": "I_kwDOAGAU1s7K0A01",
        "number": 1001,
        "title": "Upgrade to Groovy 5.0.0",
        "url": "https://github.com/user/repo1/issues/1001",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "Upgrade to Groovy 5.0.0.",
        "createdAt": "2025-09-01T10:00:00Z",
        "updatedAt": "2025-09-01T11:00:00Z",
        "closedAt": None,
        "author": {"login": "dev1", "url": "https://github.com/dev1"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo1"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A02",
        "number": 1002,
        "title": "Fix CI workflow for Java 21",
        "url": "https://github.com/user/repo1/issues/1002",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "CI build fails with Java 21. Needs workflow update.",
        "createdAt": "2025-09-02T09:20:00Z",
        "updatedAt": "2025-09-02T10:00:00Z",
        "closedAt": None,
        "author": {"login": "dev2", "url": "https://github.com/dev2"},
        "labels": {"nodes": [{"name": "status: investigating"}]},
        "repo": "user/repo1"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A03",
        "number": 1003,
        "title": "Add support for Kotlin 2.0",
        "url": "https://github.com/user/repo2/issues/1003",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Upgrade to Kotlin 2.0 and ensure compatibility.",
        "createdAt": "2025-09-03T08:15:00Z",
        "updatedAt": "2025-09-03T09:00:00Z",
        "closedAt": None,
        "author": {"login": "dev3", "url": "https://github.com/dev3"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo2"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A04",
        "number": 1004,
        "title": "Bug: NonePointerException in UserService",
        "url": "https://github.com/user/repo2/issues/1004",
        "state": "OPEN",
        "comments": {"totalCount": 3},
        "body": "UserService throws NPE when user profile is missing.",
        "createdAt": "2025-09-04T12:00:00Z",
        "updatedAt": "2025-09-04T13:00:00Z",
        "closedAt": None,
        "author": {"login": "dev4", "url": "https://github.com/dev4"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo2"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A05",
        "number": 1005,
        "title": "Refactor logging configuration",
        "url": "https://github.com/user/repo3/issues/1005",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Improve logging configuration for better debugging.",
        "createdAt": "2025-09-05T07:10:00Z",
        "updatedAt": "2025-09-05T08:00:00Z",
        "closedAt": None,
        "author": {"login": "dev5", "url": "https://github.com/dev5"},
        "labels": {"nodes": [{"name": "type: refactor"}]},
        "repo": "user/repo3"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A06",
        "number": 1006,
        "title": "Upgrade to Spring Boot 3.3.0",
        "url": "https://github.com/user/repo3/issues/1006",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Dependency upgrade required for Spring Boot 3.3.0.",
        "createdAt": "2025-09-06T09:30:00Z",
        "updatedAt": "2025-09-06T10:00:00Z",
        "closedAt": None,
        "author": {"login": "dev6", "url": "https://github.com/dev6"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo3"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A07",
        "number": 1007,
        "title": "Improve error handling in API",
        "url": "https://github.com/user/repo4/issues/1007",
        "state": "OPEN",
        "comments": {"totalCount": 5},
        "body": "API should return proper error codes instead of 500.",
        "createdAt": "2025-09-07T08:00:00Z",
        "updatedAt": "2025-09-07T09:00:00Z",
        "closedAt": None,
        "author": {"login": "dev7", "url": "https://github.com/dev7"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo4"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A08",
        "number": 1008,
        "title": "Document new configuration properties",
        "url": "https://github.com/user/repo4/issues/1008",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Add documentation for new config properties introduced.",
        "createdAt": "2025-09-08T10:00:00Z",
        "updatedAt": "2025-09-08T11:00:00Z",
        "closedAt": None,
        "author": {"login": "dev8", "url": "https://github.com/dev8"},
        "labels": {"nodes": [{"name": "type: documentation"}]},
        "repo": "user/repo4"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A09",
        "number": 1009,
        "title": "Add pagination to user list",
        "url": "https://github.com/user/repo5/issues/1009",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "User list should support pagination.",
        "createdAt": "2025-09-09T09:00:00Z",
        "updatedAt": "2025-09-09T10:00:00Z",
        "closedAt": None,
        "author": {"login": "dev9", "url": "https://github.com/dev9"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo5"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A10",
        "number": 1010,
        "title": "Fix login timeout issue",
        "url": "https://github.com/user/repo5/issues/1010",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Login session expires too early. Needs adjustment.",
        "createdAt": "2025-09-10T08:30:00Z",
        "updatedAt": "2025-09-10T09:00:00Z",
        "closedAt": None,
        "author": {"login": "dev10", "url": "https://github.com/dev10"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo5"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A11",
        "number": 1011,
        "title": "Upgrade to Hibernate 7.0",
        "url": "https://github.com/user/repo6/issues/1011",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Update project dependencies to Hibernate 7.0.",
        "createdAt": "2025-09-11T09:00:00Z",
        "updatedAt": "2025-09-11T09:30:00Z",
        "closedAt": None,
        "author": {"login": "dev11", "url": "https://github.com/dev11"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo6"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A12",
        "number": 1012,
        "title": "Bug: caching not invalidated on update",
        "url": "https://github.com/user/repo6/issues/1012",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Cache layer does not invalidate entries on update.",
        "createdAt": "2025-09-11T10:00:00Z",
        "updatedAt": "2025-09-11T11:00:00Z",
        "closedAt": None,
        "author": {"login": "dev12", "url": "https://github.com/dev12"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo6"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A13",
        "number": 1013,
        "title": "Add GraphQL endpoint for products",
        "url": "https://github.com/user/repo7/issues/1013",
        "state": "OPEN",
        "comments": {"totalCount": 3},
        "body": "Introduce GraphQL API for querying products.",
        "createdAt": "2025-09-12T09:00:00Z",
        "updatedAt": "2025-09-12T09:45:00Z",
        "closedAt": None,
        "author": {"login": "dev13", "url": "https://github.com/dev13"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo7"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A14",
        "number": 1014,
        "title": "Refactor authentication module",
        "url": "https://github.com/user/repo7/issues/1014",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Clean up and refactor authentication-related classes.",
        "createdAt": "2025-09-12T10:15:00Z",
        "updatedAt": "2025-09-12T10:45:00Z",
        "closedAt": None,
        "author": {"login": "dev14", "url": "https://github.com/dev14"},
        "labels": {"nodes": [{"name": "type: refactor"}]},
        "repo": "user/repo7"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A15",
        "number": 1015,
        "title": "Add Docker Compose for local dev",
        "url": "https://github.com/user/repo8/issues/1015",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "Provide docker-compose.yml for local environment setup.",
        "createdAt": "2025-09-13T08:20:00Z",
        "updatedAt": "2025-09-13T09:00:00Z",
        "closedAt": None,
        "author": {"login": "dev15", "url": "https://github.com/dev15"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo8"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A16",
        "number": 1016,
        "title": "Fix memory leak in Scheduler",
        "url": "https://github.com/user/repo8/issues/1016",
        "state": "OPEN",
        "comments": {"totalCount": 4},
        "body": "Scheduler retains tasks in memory after completion.",
        "createdAt": "2025-09-13T10:00:00Z",
        "updatedAt": "2025-09-13T11:00:00Z",
        "closedAt": None,
        "author": {"login": "dev16", "url": "https://github.com/dev16"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo8"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A17",
        "number": 1017,
        "title": "Add health check endpoint",
        "url": "https://github.com/user/repo9/issues/1017",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Introduce /health endpoint for monitoring.",
        "createdAt": "2025-09-14T08:00:00Z",
        "updatedAt": "2025-09-14T08:30:00Z",
        "closedAt": None,
        "author": {"login": "dev17", "url": "https://github.com/dev17"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo9"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A18",
        "number": 1018,
        "title": "Update README with setup guide",
        "url": "https://github.com/user/repo9/issues/1018",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Add setup instructions for contributors in README.",
        "createdAt": "2025-09-14T09:00:00Z",
        "updatedAt": "2025-09-14T09:45:00Z",
        "closedAt": None,
        "author": {"login": "dev18", "url": "https://github.com/dev18"},
        "labels": {"nodes": [{"name": "type: documentation"}]},
        "repo": "user/repo9"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A19",
        "number": 1019,
        "title": "Add unit tests for PaymentService",
        "url": "https://github.com/user/repo10/issues/1019",
        "state": "OPEN",
        "comments": {"totalCount": 3},
        "body": "Increase test coverage for PaymentService.",
        "createdAt": "2025-09-15T07:00:00Z",
        "updatedAt": "2025-09-15T08:00:00Z",
        "closedAt": None,
        "author": {"login": "dev19", "url": "https://github.com/dev19"},
        "labels": {"nodes": [{"name": "type: test"}]},
        "repo": "user/repo10"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A20",
        "number": 1020,
        "title": "Fix rounding issue in invoice total",
        "url": "https://github.com/user/repo10/issues/1020",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "Invoice total rounding error with certain currencies.",
        "createdAt": "2025-09-15T09:00:00Z",
        "updatedAt": "2025-09-15T09:30:00Z",
        "closedAt": None,
        "author": {"login": "dev20", "url": "https://github.com/dev20"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo10"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A21",
        "number": 1021,
        "title": "Migrate build to Gradle 9",
        "url": "https://github.com/user/repo11/issues/1021",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Update project build system to Gradle 9.",
        "createdAt": "2025-09-16T08:30:00Z",
        "updatedAt": "2025-09-16T09:00:00Z",
        "closedAt": None,
        "author": {"login": "dev21", "url": "https://github.com/dev21"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo11"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A22",
        "number": 1022,
        "title": "Add retry mechanism to API client",
        "url": "https://github.com/user/repo11/issues/1022",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Implement retry with backoff in API client.",
        "createdAt": "2025-09-16T10:00:00Z",
        "updatedAt": "2025-09-16T10:30:00Z",
        "closedAt": None,
        "author": {"login": "dev22", "url": "https://github.com/dev22"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo11"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A23",
        "number": 1023,
        "title": "Bug: file upload fails for >50MB",
        "url": "https://github.com/user/repo12/issues/1023",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "File upload limit breaks at 50MB threshold.",
        "createdAt": "2025-09-17T09:00:00Z",
        "updatedAt": "2025-09-17T09:30:00Z",
        "closedAt": None,
        "author": {"login": "dev23", "url": "https://github.com/dev23"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo12"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A24",
        "number": 1024,
        "title": "Add API docs with OpenAPI",
        "url": "https://github.com/user/repo12/issues/1024",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Generate API documentation using OpenAPI spec.",
        "createdAt": "2025-09-17T10:00:00Z",
        "updatedAt": "2025-09-17T10:20:00Z",
        "closedAt": None,
        "author": {"login": "dev24", "url": "https://github.com/dev24"},
        "labels": {"nodes": [{"name": "type: documentation"}]},
        "repo": "user/repo12"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A25",
        "number": 1025,
        "title": "Upgrade to Elasticsearch 9",
        "url": "https://github.com/user/repo13/issues/1025",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Dependency upgrade required for Elasticsearch 9.",
        "createdAt": "2025-09-18T08:00:00Z",
        "updatedAt": "2025-09-18T08:30:00Z",
        "closedAt": None,
        "author": {"login": "dev25", "url": "https://github.com/dev25"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo13"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A26",
        "number": 1026,
        "title": "Add support for multi-tenant mode",
        "url": "https://github.com/user/repo13/issues/1026",
        "state": "OPEN",
        "comments": {"totalCount": 3},
        "body": "Introduce multi-tenant support for SaaS customers.",
        "createdAt": "2025-09-18T09:00:00Z",
        "updatedAt": "2025-09-18T09:45:00Z",
        "closedAt": None,
        "author": {"login": "dev26", "url": "https://github.com/dev26"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo13"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A27",
        "number": 1027,
        "title": "Refactor notification service",
        "url": "https://github.com/user/repo14/issues/1027",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Simplify notification sending logic.",
        "createdAt": "2025-09-19T08:00:00Z",
        "updatedAt": "2025-09-19T08:30:00Z",
        "closedAt": None,
        "author": {"login": "dev27", "url": "https://github.com/dev27"},
        "labels": {"nodes": [{"name": "type: refactor"}]},
        "repo": "user/repo14"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A28",
        "number": 1028,
        "title": "Add Kafka consumer metrics",
        "url": "https://github.com/user/repo14/issues/1028",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "Expose Kafka consumer lag metrics.",
        "createdAt": "2025-09-19T09:00:00Z",
        "updatedAt": "2025-09-19T09:20:00Z",
        "closedAt": None,
        "author": {"login": "dev28", "url": "https://github.com/dev28"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo14"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A29",
        "number": 1029,
        "title": "Add rate limiting to public API",
        "url": "https://github.com/user/repo15/issues/1029",
        "state": "OPEN",
        "comments": {"totalCount": 4},
        "body": "Introduce rate limiting to avoid abuse of public API.",
        "createdAt": "2025-09-20T08:30:00Z",
        "updatedAt": "2025-09-20T09:00:00Z",
        "closedAt": None,
        "author": {"login": "dev29", "url": "https://github.com/dev29"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo15"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A30",
        "number": 1030,
        "title": "Bug: JWT token expiry mismatch",
        "url": "https://github.com/user/repo15/issues/1030",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "JWT expiry not aligned with session timeout.",
        "createdAt": "2025-09-20T10:00:00Z",
        "updatedAt": "2025-09-20T10:30:00Z",
        "closedAt": None,
        "author": {"login": "dev30", "url": "https://github.com/dev30"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo15"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A31",
        "number": 1031,
        "title": "Upgrade to PostgreSQL 16",
        "url": "https://github.com/user/repo16/issues/1031",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Update database support to PostgreSQL 16.",
        "createdAt": "2025-09-21T09:00:00Z",
        "updatedAt": "2025-09-21T09:30:00Z",
        "closedAt": None,
        "author": {"login": "dev31", "url": "https://github.com/dev31"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo16"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A32",
        "number": 1032,
        "title": "Add audit logging",
        "url": "https://github.com/user/repo16/issues/1032",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Introduce audit logging for sensitive operations.",
        "createdAt": "2025-09-21T10:00:00Z",
        "updatedAt": "2025-09-21T10:30:00Z",
        "closedAt": None,
        "author": {"login": "dev32", "url": "https://github.com/dev32"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo16"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A33",
        "number": 1033,
        "title": "Refactor configuration loading",
        "url": "https://github.com/user/repo17/issues/1033",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Unify configuration loading logic across modules.",
        "createdAt": "2025-09-22T08:00:00Z",
        "updatedAt": "2025-09-22T08:30:00Z",
        "closedAt": None,
        "author": {"login": "dev33", "url": "https://github.com/dev33"},
        "labels": {"nodes": [{"name": "type: refactor"}]},
        "repo": "user/repo17"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A34",
        "number": 1034,
        "title": "Bug: config reload not applied",
        "url": "https://github.com/user/repo17/issues/1034",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "Configuration reload endpoint does not refresh values.",
        "createdAt": "2025-09-22T09:00:00Z",
        "updatedAt": "2025-09-22T09:20:00Z",
        "closedAt": None,
        "author": {"login": "dev34", "url": "https://github.com/dev34"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo17"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A35",
        "number": 1035,
        "title": "Add CI badge to README",
        "url": "https://github.com/user/repo18/issues/1035",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Display GitHub Actions CI status in README.",
        "createdAt": "2025-09-23T08:00:00Z",
        "updatedAt": "2025-09-23T08:15:00Z",
        "closedAt": None,
        "author": {"login": "dev35", "url": "https://github.com/dev35"},
        "labels": {"nodes": [{"name": "type: documentation"}]},
        "repo": "user/repo18"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A36",
        "number": 1036,
        "title": "Add support for dark mode UI",
        "url": "https://github.com/user/repo18/issues/1036",
        "state": "OPEN",
        "comments": {"totalCount": 3},
        "body": "Implement dark mode toggle in frontend.",
        "createdAt": "2025-09-23T09:00:00Z",
        "updatedAt": "2025-09-23T09:30:00Z",
        "closedAt": None,
        "author": {"login": "dev36", "url": "https://github.com/dev36"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo18"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A37",
        "number": 1037,
        "title": "Upgrade to Node.js 22",
        "url": "https://github.com/user/repo19/issues/1037",
        "state": "OPEN",
        "comments": {"totalCount": 1},
        "body": "Update build to support Node.js 22.",
        "createdAt": "2025-09-24T08:00:00Z",
        "updatedAt": "2025-09-24T08:20:00Z",
        "closedAt": None,
        "author": {"login": "dev37", "url": "https://github.com/dev37"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo19"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A38",
        "number": 1038,
        "title": "Bug: WebSocket disconnects unexpectedly",
        "url": "https://github.com/user/repo19/issues/1038",
        "state": "OPEN",
        "comments": {"totalCount": 2},
        "body": "WebSocket connections drop without error logs.",
        "createdAt": "2025-09-24T09:00:00Z",
        "updatedAt": "2025-09-24T09:15:00Z",
        "closedAt": None,
        "author": {"login": "dev38", "url": "https://github.com/dev38"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo19"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A39",
        "number": 1039,
        "title": "Refactor frontend build pipeline",
        "url": "https://github.com/user/repo20/issues/1039",
        "state": "OPEN",
        "comments": {"totalCount": 0},
        "body": "Simplify and speed up frontend build process.",
        "createdAt": "2025-09-25T08:00:00Z",
        "updatedAt": "2025-09-25T08:30:00Z",
        "closedAt": None,
        "author": {"login": "dev39", "url": "https://github.com/dev39"},
        "labels": {"nodes": [{"name": "type: refactor"}]},
        "repo": "user/repo20"
    },
    {
        "_id": "I_kwDOAGAU1s7K0A40",
        "number": 1040,
        "title": "Add end-to-end tests",
        "url": "https://github.com/user/repo20/issues/1040",
        "state": "OPEN",
        "comments": {"totalCount": 4},
        "body": "Introduce Cypress end-to-end tests for main flows.",
        "createdAt": "2025-09-25T09:00:00Z",
        "updatedAt": "2025-09-25T09:20:00Z",
        "closedAt": None,
        "author": {"login": "dev40", "url": "https://github.com/dev40"},
        "labels": {"nodes": [{"name": "type: test"}]},
        "repo": "user/repo20"
    }
]

TEST_PULLS = [
    {
        "_id": "PR_kwDOAGAU1s6nZ900",
        "number": 2001,
        "title": "Upgrade Gradle wrapper to 8.5",
        "url": "https://github.com/user/repo1/pull/2001",
        "state": "MERGED",
        "comments": {"totalCount": 2},
        "body": "Upgrade Gradle wrapper to version 8.5 to support new build features.",
        "createdAt": "2025-09-01T09:00:00Z",
        "updatedAt": "2025-09-01T10:00:00Z",
        "closedAt": "2025-09-01T10:00:00Z",
        "author": {"login": "dev1", "url": "https://github.com/dev1"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo1"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ901",
        "number": 2002,
        "title": "Fix NullPointerException in OrderService",
        "url": "https://github.com/user/repo1/pull/2002",
        "state": "CLOSED",
        "comments": {"totalCount": 1},
        "body": "Fix potential NPE in OrderService when order details are missing.",
        "createdAt": "2025-09-02T08:30:00Z",
        "updatedAt": "2025-09-02T09:30:00Z",
        "closedAt": "2025-09-02T09:30:00Z",
        "author": {"login": "dev2", "url": "https://github.com/dev2"},
        "labels": {"nodes": [{"name": "type: bug"}]},
        "repo": "user/repo1"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ902",
        "number": 2003,
        "title": "Add support for Kotlin 2.0",
        "url": "https://github.com/user/repo2/pull/2003",
        "state": "OPEN",
        "comments": {"totalCount": 3},
        "body": "Introduce support for Kotlin 2.0 and update Gradle plugins accordingly.",
        "createdAt": "2025-09-03T09:00:00Z",
        "updatedAt": "2025-09-03T11:00:00Z",
        "closedAt": None,
        "author": {"login": "dev3", "url": "https://github.com/dev3"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo2"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ903",
        "number": 2004,
        "title": "Refactor logging configuration",
        "url": "https://github.com/user/repo2/pull/2004",
        "state": "MERGED",
        "comments": {"totalCount": 0},
        "body": "Refactor logging setup to centralize configuration in application.yml.",
        "createdAt": "2025-09-04T12:00:00Z",
        "updatedAt": "2025-09-04T13:00:00Z",
        "closedAt": "2025-09-04T13:00:00Z",
        "author": {"login": "dev4", "url": "https://github.com/dev4"},
        "labels": {"nodes": [{"name": "type: refactor"}]},
        "repo": "user/repo2"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ904",
        "number": 2005,
        "title": "Implement caching in ProductService",
        "url": "https://github.com/user/repo3/pull/2005",
        "state": "OPEN",
        "comments": {"totalCount": 4},
        "body": "Add caching layer using Spring Cache for ProductService results.",
        "createdAt": "2025-09-05T10:00:00Z",
        "updatedAt": "2025-09-05T11:00:00Z",
        "closedAt": None,
        "author": {"login": "dev5", "url": "https://github.com/dev5"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo3"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ905",
        "number": 2006,
        "title": "Upgrade to Spring Boot 3.3.0",
        "url": "https://github.com/user/repo3/pull/2006",
        "state": "MERGED",
        "comments": {"totalCount": 1},
        "body": "Upgrade dependencies to Spring Boot 3.3.0.",
        "createdAt": "2025-09-06T09:00:00Z",
        "updatedAt": "2025-09-06T10:00:00Z",
        "closedAt": "2025-09-06T10:00:00Z",
        "author": {"login": "dev6", "url": "https://github.com/dev6"},
        "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
        "repo": "user/repo3"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ906",
        "number": 2007,
        "title": "Improve error handling in API",
        "url": "https://github.com/user/repo4/pull/2007",
        "state": "CLOSED",
        "comments": {"totalCount": 2},
        "body": "Return proper error codes instead of generic 500s.",
        "createdAt": "2025-09-07T08:00:00Z",
        "updatedAt": "2025-09-07T09:00:00Z",
        "closedAt": "2025-09-07T09:00:00Z",
        "author": {"login": "dev7", "url": "https://github.com/dev7"},
        "labels": {"nodes": [{"name": "type: enhancement"}]},
        "repo": "user/repo4"
    },
    {
        "_id": "PR_kwDOAGAU1s6nZ907",
        "number": 2008,
        "title": "Document new configuration properties",
        "url": "https://github.com/user/repo4/pull/2008",
        "state": "MERGED",
        "comments": {"totalCount": 1},
        "body": "Add documentation for recently introduced config properties.",
        "createdAt": "2025-09-08T10:00:00Z",
        "updatedAt": "2025-09-08T11:00:00Z",
        "closedAt": "2025-09-08T11:00:00Z",
        "author": {"login": "dev8", "url": "https://github.com/dev8"},
        "labels": {"nodes": [{"name": "type: documentation"}]},
        "repo": "user/repo4"
    }, [
        {
            "_id": "PR_kwDOAGAU1s6nZ908",
            "number": 2009,
            "title": "Add unit tests for PaymentService",
            "url": "https://github.com/user/repo5/pull/2009",
            "state": "OPEN",
            "comments": {"totalCount": 0},
            "body": "Introduce JUnit tests for PaymentService to improve coverage.",
            "createdAt": "2025-09-09T08:00:00Z",
            "updatedAt": "2025-09-09T09:00:00Z",
            "closedAt": None,
            "author": {"login": "dev9", "url": "https://github.com/dev9"},
            "labels": {"nodes": [{"name": "type: test"}]},
            "repo": "user/repo5"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ909",
            "number": 2010,
            "title": "Fix memory leak in cache module",
            "url": "https://github.com/user/repo5/pull/2010",
            "state": "MERGED",
            "comments": {"totalCount": 1},
            "body": "Resolve memory leak caused by improper cache eviction strategy.",
            "createdAt": "2025-09-09T10:00:00Z",
            "updatedAt": "2025-09-09T11:00:00Z",
            "closedAt": "2025-09-09T11:00:00Z",
            "author": {"login": "dev10", "url": "https://github.com/dev10"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo5"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ90A",
            "number": 2011,
            "title": "Refactor database migration scripts",
            "url": "https://github.com/user/repo6/pull/2011",
            "state": "MERGED",
            "comments": {"totalCount": 2},
            "body": "Refactor Flyway migration scripts for clarity and maintainability.",
            "createdAt": "2025-09-10T09:00:00Z",
            "updatedAt": "2025-09-10T09:30:00Z",
            "closedAt": "2025-09-10T09:30:00Z",
            "author": {"login": "dev11", "url": "https://github.com/dev11"},
            "labels": {"nodes": [{"name": "type: refactor"}]},
            "repo": "user/repo6"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ90B",
            "number": 2012,
            "title": "Add Docker Compose support",
            "url": "https://github.com/user/repo6/pull/2012",
            "state": "OPEN",
            "comments": {"totalCount": 3},
            "body": "Introduce Docker Compose setup for local development.",
            "createdAt": "2025-09-10T10:00:00Z",
            "updatedAt": "2025-09-10T11:00:00Z",
            "closedAt": None,
            "author": {"login": "dev12", "url": "https://github.com/dev12"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo6"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ90C",
            "number": 2013,
            "title": "Update dependencies to latest versions",
            "url": "https://github.com/user/repo7/pull/2013",
            "state": "CLOSED",
            "comments": {"totalCount": 0},
            "body": "Update third-party libraries to latest stable versions.",
            "createdAt": "2025-09-11T09:00:00Z",
            "updatedAt": "2025-09-11T09:20:00Z",
            "closedAt": "2025-09-11T09:20:00Z",
            "author": {"login": "dev13", "url": "https://github.com/dev13"},
            "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
            "repo": "user/repo7"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ90D",
            "number": 2014,
            "title": "Improve startup time by optimizing bean loading",
            "url": "https://github.com/user/repo7/pull/2014",
            "state": "MERGED",
            "comments": {"totalCount": 1},
            "body": "Optimize Spring context initialization to reduce startup time.",
            "createdAt": "2025-09-11T10:00:00Z",
            "updatedAt": "2025-09-11T11:00:00Z",
            "closedAt": "2025-09-11T11:00:00Z",
            "author": {"login": "dev14", "url": "https://github.com/dev14"},
            "labels": {"nodes": [{"name": "type: performance"}]},
            "repo": "user/repo7"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ90E",
            "number": 2015,
            "title": "Implement OAuth2 login",
            "url": "https://github.com/user/repo8/pull/2015",
            "state": "OPEN",
            "comments": {"totalCount": 5},
            "body": "Add support for OAuth2 login with Google and GitHub providers.",
            "createdAt": "2025-09-12T09:00:00Z",
            "updatedAt": "2025-09-12T10:00:00Z",
            "closedAt": None,
            "author": {"login": "dev15", "url": "https://github.com/dev15"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo8"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ90F",
            "number": 2016,
            "title": "Bug: fix logout redirect issue",
            "url": "https://github.com/user/repo8/pull/2016",
            "state": "CLOSED",
            "comments": {"totalCount": 2},
            "body": "Fixes logout redirect not clearing session properly.",
            "createdAt": "2025-09-12T11:00:00Z",
            "updatedAt": "2025-09-12T12:00:00Z",
            "closedAt": "2025-09-12T12:00:00Z",
            "author": {"login": "dev16", "url": "https://github.com/dev16"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo8"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ910",
            "number": 2017,
            "title": "Refactor notification service",
            "url": "https://github.com/user/repo9/pull/2017",
            "state": "MERGED",
            "comments": {"totalCount": 1},
            "body": "Refactor notification service to use async event publishing.",
            "createdAt": "2025-09-13T08:00:00Z",
            "updatedAt": "2025-09-13T08:30:00Z",
            "closedAt": "2025-09-13T08:30:00Z",
            "author": {"login": "dev17", "url": "https://github.com/dev17"},
            "labels": {"nodes": [{"name": "type: refactor"}]},
            "repo": "user/repo9"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ911",
            "number": 2018,
            "title": "Add retry mechanism to API client",
            "url": "https://github.com/user/repo9/pull/2018",
            "state": "OPEN",
            "comments": {"totalCount": 4},
            "body": "Add retry logic to API client for transient network errors.",
            "createdAt": "2025-09-13T09:00:00Z",
            "updatedAt": "2025-09-13T09:30:00Z",
            "closedAt": None,
            "author": {"login": "dev18", "url": "https://github.com/dev18"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo9"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ912",
            "number": 2019,
            "title": "Add GraphQL support",
            "url": "https://github.com/user/repo10/pull/2019",
            "state": "MERGED",
            "comments": {"totalCount": 3},
            "body": "Introduce GraphQL endpoint alongside REST API.",
            "createdAt": "2025-09-14T08:00:00Z",
            "updatedAt": "2025-09-14T09:00:00Z",
            "closedAt": "2025-09-14T09:00:00Z",
            "author": {"login": "dev19", "url": "https://github.com/dev19"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo10"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ913",
            "number": 2020,
            "title": "Fix pagination bug in search API",
            "url": "https://github.com/user/repo10/pull/2020",
            "state": "CLOSED",
            "comments": {"totalCount": 1},
            "body": "Resolve off-by-one error in search API pagination logic.",
            "createdAt": "2025-09-14T10:00:00Z",
            "updatedAt": "2025-09-14T11:00:00Z",
            "closedAt": "2025-09-14T11:00:00Z",
            "author": {"login": "dev20", "url": "https://github.com/dev20"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo10"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ914",
            "number": 2021,
            "title": "Upgrade to Hibernate 7",
            "url": "https://github.com/user/repo11/pull/2021",
            "state": "OPEN",
            "comments": {"totalCount": 2},
            "body": "Upgrade ORM layer to Hibernate 7 for performance improvements.",
            "createdAt": "2025-09-15T09:00:00Z",
            "updatedAt": "2025-09-15T10:00:00Z",
            "closedAt": None,
            "author": {"login": "dev21", "url": "https://github.com/dev21"},
            "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
            "repo": "user/repo11"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ915",
            "number": 2022,
            "title": "Bug: fix transaction rollback issue",
            "url": "https://github.com/user/repo11/pull/2022",
            "state": "MERGED",
            "comments": {"totalCount": 0},
            "body": "Ensure transaction rollback works correctly when exception is thrown.",
            "createdAt": "2025-09-15T11:00:00Z",
            "updatedAt": "2025-09-15T11:30:00Z",
            "closedAt": "2025-09-15T11:30:00Z",
            "author": {"login": "dev22", "url": "https://github.com/dev22"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo11"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ916",
            "number": 2023,
            "title": "Add CI pipeline for integration tests",
            "url": "https://github.com/user/repo12/pull/2023",
            "state": "MERGED",
            "comments": {"totalCount": 2},
            "body": "Introduce GitHub Actions workflow to run integration tests.",
            "createdAt": "2025-09-16T08:00:00Z",
            "updatedAt": "2025-09-16T09:00:00Z",
            "closedAt": "2025-09-16T09:00:00Z",
            "author": {"login": "dev23", "url": "https://github.com/dev23"},
            "labels": {"nodes": [{"name": "type: test"}]},
            "repo": "user/repo12"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ917",
            "number": 2024,
            "title": "Refactor error response handling",
            "url": "https://github.com/user/repo12/pull/2024",
            "state": "CLOSED",
            "comments": {"totalCount": 1},
            "body": "Refactor error responses to use standard error format.",
            "createdAt": "2025-09-16T10:00:00Z",
            "updatedAt": "2025-09-16T10:30:00Z",
            "closedAt": "2025-09-16T10:30:00Z",
            "author": {"login": "dev24", "url": "https://github.com/dev24"},
            "labels": {"nodes": [{"name": "type: refactor"}]},
            "repo": "user/repo12"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ918",
            "number": 2025,
            "title": "Add Redis support for caching",
            "url": "https://github.com/user/repo13/pull/2025",
            "state": "OPEN",
            "comments": {"totalCount": 4},
            "body": "Introduce Redis as caching provider.",
            "createdAt": "2025-09-17T09:00:00Z",
            "updatedAt": "2025-09-17T10:00:00Z",
            "closedAt": None,
            "author": {"login": "dev25", "url": "https://github.com/dev25"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo13"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ919",
            "number": 2026,
            "title": "Bug: fix cache invalidation issue",
            "url": "https://github.com/user/repo13/pull/2026",
            "state": "MERGED",
            "comments": {"totalCount": 1},
            "body": "Ensure cache invalidation works correctly on updates.",
            "createdAt": "2025-09-17T11:00:00Z",
            "updatedAt": "2025-09-17T11:30:00Z",
            "closedAt": "2025-09-17T11:30:00Z",
            "author": {"login": "dev26", "url": "https://github.com/dev26"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo13"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91A",
            "number": 2027,
            "title": "Refactor CI workflows",
            "url": "https://github.com/user/repo14/pull/2027",
            "state": "CLOSED",
            "comments": {"totalCount": 0},
            "body": "Simplify CI workflows and reuse shared steps.",
            "createdAt": "2025-09-18T08:00:00Z",
            "updatedAt": "2025-09-18T08:30:00Z",
            "closedAt": "2025-09-18T08:30:00Z",
            "author": {"login": "dev27", "url": "https://github.com/dev27"},
            "labels": {"nodes": [{"name": "type: refactor"}]},
            "repo": "user/repo14"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91B",
            "number": 2028,
            "title": "Upgrade Node.js version in pipeline",
            "url": "https://github.com/user/repo14/pull/2028",
            "state": "MERGED",
            "comments": {"totalCount": 2},
            "body": "Update CI pipeline to use Node.js 22.",
            "createdAt": "2025-09-18T09:00:00Z",
            "updatedAt": "2025-09-18T09:20:00Z",
            "closedAt": "2025-09-18T09:20:00Z",
            "author": {"login": "dev28", "url": "https://github.com/dev28"},
            "labels": {"nodes": [{"name": "type: dependency-upgrade"}]},
            "repo": "user/repo14"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91C",
            "number": 2029,
            "title": "Implement rate limiting",
            "url": "https://github.com/user/repo15/pull/2029",
            "state": "OPEN",
            "comments": {"totalCount": 5},
            "body": "Add rate limiting to API to prevent abuse.",
            "createdAt": "2025-09-19T09:00:00Z",
            "updatedAt": "2025-09-19T10:00:00Z",
            "closedAt": None,
            "author": {"login": "dev29", "url": "https://github.com/dev29"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo15"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91D",
            "number": 2030,
            "title": "Fix security issue in JWT validation",
            "url": "https://github.com/user/repo15/pull/2030",
            "state": "MERGED",
            "comments": {"totalCount": 3},
            "body": "Fix security vulnerability in JWT signature verification.",
            "createdAt": "2025-09-19T11:00:00Z",
            "updatedAt": "2025-09-19T11:30:00Z",
            "closedAt": "2025-09-19T11:30:00Z",
            "author": {"login": "dev30", "url": "https://github.com/dev30"},
            "labels": {"nodes": [{"name": "type: security"}]},
            "repo": "user/repo15"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91E",
            "number": 2031,
            "title": "Refactor frontend components to React 19",
            "url": "https://github.com/user/repo16/pull/2031",
            "state": "OPEN",
            "comments": {"totalCount": 1},
            "body": "Upgrade and refactor frontend components to React 19.",
            "createdAt": "2025-09-20T08:00:00Z",
            "updatedAt": "2025-09-20T09:00:00Z",
            "closedAt": None,
            "author": {"login": "dev31", "url": "https://github.com/dev31"},
            "labels": {"nodes": [{"name": "type: refactor"}]},
            "repo": "user/repo16"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91F",
            "number": 2032,
            "title": "Add dark mode support",
            "url": "https://github.com/user/repo16/pull/2032",
            "state": "MERGED",
            "comments": {"totalCount": 4},
            "body": "Implement dark mode theme for frontend.",
            "createdAt": "2025-09-20T10:00:00Z",
            "updatedAt": "2025-09-20T11:00:00Z",
            "closedAt": "2025-09-20T11:00:00Z",
            "author": {"login": "dev32", "url": "https://github.com/dev32"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo16"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91G",
            "number": 2033,
            "title": "Add email verification flow",
            "url": "https://github.com/user/repo17/pull/2033",
            "state": "CLOSED",
            "comments": {"totalCount": 0},
            "body": "Implement email verification for new users.",
            "createdAt": "2025-09-21T08:00:00Z",
            "updatedAt": "2025-09-21T08:30:00Z",
            "closedAt": "2025-09-21T08:30:00Z",
            "author": {"login": "dev33", "url": "https://github.com/dev33"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo17"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91H",
            "number": 2034,
            "title": "Fix bug in password reset flow",
            "url": "https://github.com/user/repo17/pull/2034",
            "state": "MERGED",
            "comments": {"totalCount": 2},
            "body": "Fix password reset token not expiring correctly.",
            "createdAt": "2025-09-21T09:00:00Z",
            "updatedAt": "2025-09-21T09:30:00Z",
            "closedAt": "2025-09-21T09:30:00Z",
            "author": {"login": "dev34", "url": "https://github.com/dev34"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo17"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91I",
            "number": 2035,
            "title": "Add Kubernetes manifests",
            "url": "https://github.com/user/repo18/pull/2035",
            "state": "MERGED",
            "comments": {"totalCount": 3},
            "body": "Introduce Kubernetes deployment manifests.",
            "createdAt": "2025-09-22T08:00:00Z",
            "updatedAt": "2025-09-22T08:30:00Z",
            "closedAt": "2025-09-22T08:30:00Z",
            "author": {"login": "dev35", "url": "https://github.com/dev35"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo18"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91J",
            "number": 2036,
            "title": "Refactor logging configuration",
            "url": "https://github.com/user/repo18/pull/2036",
            "state": "OPEN",
            "comments": {"totalCount": 1},
            "body": "Refactor logging setup to use structured JSON logs.",
            "createdAt": "2025-09-22T09:00:00Z",
            "updatedAt": "2025-09-22T09:20:00Z",
            "closedAt": None,
            "author": {"login": "dev36", "url": "https://github.com/dev36"},
            "labels": {"nodes": [{"name": "type: refactor"}]},
            "repo": "user/repo18"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91K",
            "number": 2037,
            "title": "Add SSO with SAML",
            "url": "https://github.com/user/repo19/pull/2037",
            "state": "CLOSED",
            "comments": {"totalCount": 2},
            "body": "Implement Single Sign-On using SAML.",
            "createdAt": "2025-09-23T08:00:00Z",
            "updatedAt": "2025-09-23T09:00:00Z",
            "closedAt": "2025-09-23T09:00:00Z",
            "author": {"login": "dev37", "url": "https://github.com/dev37"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo19"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91L",
            "number": 2038,
            "title": "Bug: fix user roles not updating",
            "url": "https://github.com/user/repo19/pull/2038",
            "state": "MERGED",
            "comments": {"totalCount": 0},
            "body": "Ensure user role updates propagate correctly in system.",
            "createdAt": "2025-09-23T10:00:00Z",
            "updatedAt": "2025-09-23T10:20:00Z",
            "closedAt": "2025-09-23T10:20:00Z",
            "author": {"login": "dev38", "url": "https://github.com/dev38"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo19"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91M",
            "number": 2039,
            "title": "Add monitoring with Prometheus",
            "url": "https://github.com/user/repo20/pull/2039",
            "state": "OPEN",
            "comments": {"totalCount": 3},
            "body": "Integrate Prometheus metrics collection.",
            "createdAt": "2025-09-24T08:00:00Z",
            "updatedAt": "2025-09-24T09:00:00Z",
            "closedAt": None,
            "author": {"login": "dev39", "url": "https://github.com/dev39"},
            "labels": {"nodes": [{"name": "type: enhancement"}]},
            "repo": "user/repo20"
        },
        {
            "_id": "PR_kwDOAGAU1s6nZ91N",
            "number": 2040,
            "title": "Fix alertmanager config bug",
            "url": "https://github.com/user/repo20/pull/2040",
            "state": "MERGED",
            "comments": {"totalCount": 1},
            "body": "Fixes bug in alertmanager configuration for Slack alerts.",
            "createdAt": "2025-09-24T10:00:00Z",
            "updatedAt": "2025-09-24T10:20:00Z",
            "closedAt": "2025-09-24T10:20:00Z",
            "author": {"login": "dev40", "url": "https://github.com/dev40"},
            "labels": {"nodes": [{"name": "type: bug"}]},
            "repo": "user/repo20"
        }
    ]

]

LANGUAGES = ['Swift', 'Shell', 'Dart', 'C++', 'JavaScript', 'TypeScript', 'Rust', 'C#', 'Python', 'PHP', 'Haskell',
             'Java', 'Kotlin', 'Scala', 'Objective-C', 'Elixir', 'Perl', 'Ruby', 'Go']

MAXES = {
    "stars_count": 50,
    "watchers_count": 20,
    "forks_count": 12,
    "issue_count": 7,
    "pr_count": 4,
    "workflows_count": 5
}
