# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CommentAuthor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, url: str=None, association: str=None):  # noqa: E501
        """CommentAuthor - a model defined in Swagger

        :param name: The name of this CommentAuthor.  # noqa: E501
        :type name: str
        :param url: The url of this CommentAuthor.  # noqa: E501
        :type url: str
        :param association: The association of this CommentAuthor.  # noqa: E501
        :type association: str
        """
        self.swagger_types = {
            'name': str,
            'url': str,
            'association': str
        }

        self.attribute_map = {
            'name': 'name',
            'url': 'url',
            'association': 'association'
        }
        self._name = name
        self._url = url
        self._association = association

    @classmethod
    def from_dict(cls, dikt) -> 'CommentAuthor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Comment_author of this CommentAuthor.  # noqa: E501
        :rtype: CommentAuthor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CommentAuthor.


        :return: The name of this CommentAuthor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CommentAuthor.


        :param name: The name of this CommentAuthor.
        :type name: str
        """

        self._name = name

    @property
    def url(self) -> str:
        """Gets the url of this CommentAuthor.


        :return: The url of this CommentAuthor.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this CommentAuthor.


        :param url: The url of this CommentAuthor.
        :type url: str
        """

        self._url = url

    @property
    def association(self) -> str:
        """Gets the association of this CommentAuthor.


        :return: The association of this CommentAuthor.
        :rtype: str
        """
        return self._association

    @association.setter
    def association(self, association: str):
        """Sets the association of this CommentAuthor.


        :param association: The association of this CommentAuthor.
        :type association: str
        """
        allowed_values = ["CONTRIBUTOR", "NONE", "COLLABORATOR", "MEMBER"]  # noqa: E501
        if association not in allowed_values:
            raise ValueError(
                "Invalid value for `association` ({0}), must be one of {1}"
                .format(association, allowed_values)
            )

        self._association = association
