# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.issue import Issue  # noqa: F401,E501
from swagger_server.models.result import Result  # noqa: F401,E501
from swagger_server import util


class IssuesList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[Issue]=None, page: int=None, total_elements: int=None):  # noqa: E501
        """IssuesList - a model defined in Swagger

        :param items: The items of this IssuesList.  # noqa: E501
        :type items: List[Issue]
        :param page: The page of this IssuesList.  # noqa: E501
        :type page: int
        :param total_elements: The total_elements of this IssuesList.  # noqa: E501
        :type total_elements: int
        """
        self.swagger_types = {
            'items': List[Issue],
            'page': int,
            'total_elements': int
        }

        self.attribute_map = {
            'items': 'items',
            'page': 'page',
            'total_elements': 'totalElements'
        }
        self._items = items
        self._page = page
        self._total_elements = total_elements

    @classmethod
    def from_dict(cls, dikt) -> 'IssuesList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IssuesList of this IssuesList.  # noqa: E501
        :rtype: IssuesList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[Issue]:
        """Gets the items of this IssuesList.


        :return: The items of this IssuesList.
        :rtype: List[Issue]
        """
        return self._items

    @items.setter
    def items(self, items: List[Issue]):
        """Sets the items of this IssuesList.


        :param items: The items of this IssuesList.
        :type items: List[Issue]
        """

        self._items = items

    @property
    def page(self) -> int:
        """Gets the page of this IssuesList.


        :return: The page of this IssuesList.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this IssuesList.


        :param page: The page of this IssuesList.
        :type page: int
        """

        self._page = page

    @property
    def total_elements(self) -> int:
        """Gets the total_elements of this IssuesList.


        :return: The total_elements of this IssuesList.
        :rtype: int
        """
        return self._total_elements

    @total_elements.setter
    def total_elements(self, total_elements: int):
        """Sets the total_elements of this IssuesList.


        :param total_elements: The total_elements of this IssuesList.
        :type total_elements: int
        """

        self._total_elements = total_elements
