# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MapStringNumber(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stats: Dict[str, int]=None):  # noqa: E501
        """MapStringNumber - a model defined in Swagger

        :param stats: The stats of this MapStringNumber.  # noqa: E501
        :type stats: Dict[str, int]
        """
        self.swagger_types = {
            'stats': Dict[str, int]
        }

        self.attribute_map = {
            'stats': 'stats'
        }
        self._stats = stats

    @classmethod
    def from_dict(cls, dikt) -> 'MapStringNumber':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MapStringNumber of this MapStringNumber.  # noqa: E501
        :rtype: MapStringNumber
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stats(self) -> Dict[str, int]:
        """Gets the stats of this MapStringNumber.


        :return: The stats of this MapStringNumber.
        :rtype: Dict[str, int]
        """
        return self._stats

    @stats.setter
    def stats(self, stats: Dict[str, int]):
        """Sets the stats of this MapStringNumber.


        :param stats: The stats of this MapStringNumber.
        :type stats: Dict[str, int]
        """

        self._stats = stats
