# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class Metrics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, languages: List[str] = None, maxes: Dict[str, int] = None):  # noqa: E501
        """Metrics - a model defined in Swagger

        :param languages: The languages of this Metrics.  # noqa: E501
        :type languages: List[str]
        :param maxes: The maxes of this Metrics.  # noqa: E501
        :type maxes: Dict[str, int]
        """
        self.swagger_types = {
            'languages': List[str],
            'maxes': Dict[str, int]
        }

        self.attribute_map = {
            'languages': 'languages',
            'maxes': 'maxes'
        }
        self._languages = languages
        self._maxes = maxes

    @classmethod
    def from_dict(cls, dikt) -> 'Metrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metrics of this Metrics.  # noqa: E501
        :rtype: Metrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def languages(self) -> List[str]:
        """Gets the languages of this Metrics.


        :return: The languages of this Metrics.
        :rtype: List[str]
        """
        return self._languages

    @languages.setter
    def languages(self, languages: List[str]):
        """Sets the languages of this Metrics.


        :param languages: The languages of this Metrics.
        :type languages: List[str]
        """

        self._languages = languages

    @property
    def maxes(self) -> Dict[str, int]:
        """Gets the maxes of this Metrics.


        :return: The maxes of this Metrics.
        :rtype: Dict[str, int]
        """
        return self._maxes

    @maxes.setter
    def maxes(self, maxes: Dict[str, int]):
        """Sets the maxes of this Metrics.


        :param maxes: The maxes of this Metrics.
        :type maxes: Dict[str, int]
        """

        self._maxes = maxes
