# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.repository import Repository  # noqa: F401,E501
from swagger_server.models.result import Result  # noqa: F401,E501


class RepositoriesList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, items: List[Repository] = None, page: int = None, total_elements: int = None):  # noqa: E501
        """RepositoriesList - a model defined in Swagger

        :param items: The items of this RepositoriesList.  # noqa: E501
        :type items: List[Repository]
        :param page: The page of this RepositoriesList.  # noqa: E501
        :type page: int
        :param total_elements: The total_elements of this RepositoriesList.  # noqa: E501
        :type total_elements: int
        """
        self.swagger_types = {
            'items': List[Repository],
            'page': int,
            'total_elements': int
        }

        self.attribute_map = {
            'items': 'items',
            'page': 'page',
            'total_elements': 'total_elements'
        }
        self._items = items
        self._page = page
        self._total_elements = total_elements

    @classmethod
    def from_dict(cls, dikt) -> 'RepositoriesList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RepositoriesList of this RepositoriesList.  # noqa: E501
        :rtype: RepositoriesList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[Repository]:
        """Gets the items of this RepositoriesList.


        :return: The items of this RepositoriesList.
        :rtype: List[Repository]
        """
        return self._items

    @items.setter
    def items(self, items: List[Repository]):
        """Sets the items of this RepositoriesList.


        :param items: The items of this RepositoriesList.
        :type items: List[Repository]
        """

        self._items = items

    @property
    def page(self) -> int:
        """Gets the page of this RepositoriesList.


        :return: The page of this RepositoriesList.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this RepositoriesList.


        :param page: The page of this RepositoriesList.
        :type page: int
        """

        self._page = page

    @property
    def total_elements(self) -> int:
        """Gets the total_elements of this RepositoriesList.


        :return: The total_elements of this RepositoriesList.
        :rtype: int
        """
        return self._total_elements

    @total_elements.setter
    def total_elements(self, total_elements: int):
        """Sets the total_elements of this RepositoriesList.


        :param total_elements: The total_elements of this RepositoriesList.
        :type total_elements: int
        """

        self._total_elements = total_elements
