# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.map_string_number import MapStringNumber  # noqa: F401,E501
from swagger_server import util


class StatisticsWorkflows(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, daily_runs: MapStringNumber=None, type_runs: MapStringNumber=None):  # noqa: E501
        """StatisticsWorkflows - a model defined in Swagger

        :param daily_runs: The daily_runs of this StatisticsWorkflows.  # noqa: E501
        :type daily_runs: MapStringNumber
        :param type_runs: The type_runs of this StatisticsWorkflows.  # noqa: E501
        :type type_runs: MapStringNumber
        """
        self.swagger_types = {
            'daily_runs': MapStringNumber,
            'type_runs': MapStringNumber
        }

        self.attribute_map = {
            'daily_runs': 'dailyRuns',
            'type_runs': 'typeRuns'
        }
        self._daily_runs = daily_runs
        self._type_runs = type_runs

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsWorkflows':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_workflows of this StatisticsWorkflows.  # noqa: E501
        :rtype: StatisticsWorkflows
        """
        return util.deserialize_model(dikt, cls)

    @property
    def daily_runs(self) -> MapStringNumber:
        """Gets the daily_runs of this StatisticsWorkflows.


        :return: The daily_runs of this StatisticsWorkflows.
        :rtype: MapStringNumber
        """
        return self._daily_runs

    @daily_runs.setter
    def daily_runs(self, daily_runs: MapStringNumber):
        """Sets the daily_runs of this StatisticsWorkflows.


        :param daily_runs: The daily_runs of this StatisticsWorkflows.
        :type daily_runs: MapStringNumber
        """

        self._daily_runs = daily_runs

    @property
    def type_runs(self) -> MapStringNumber:
        """Gets the type_runs of this StatisticsWorkflows.


        :return: The type_runs of this StatisticsWorkflows.
        :rtype: MapStringNumber
        """
        return self._type_runs

    @type_runs.setter
    def type_runs(self, type_runs: MapStringNumber):
        """Sets the type_runs of this StatisticsWorkflows.


        :param type_runs: The type_runs of this StatisticsWorkflows.
        :type type_runs: MapStringNumber
        """

        self._type_runs = type_runs
