# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.map_string_number import MapStringNumber  # noqa: F401,E501
from swagger_server import util


class StatisticsWorkflows(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metrics: MapStringNumber=None):  # noqa: E501
        """StatisticsWorkflows - a model defined in Swagger

        :param metrics: The daily_runs of this StatisticsWorkflows.  # noqa: E501
        :type metrics: MapStringNumber
        """
        self.swagger_types = {
            'metrics': MapStringNumber
        }

        self.attribute_map = {
            'metrics': 'metrics'
        }
        self._metrics = metrics

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsWorkflows':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_workflows of this StatisticsWorkflows.  # noqa: E501
        :rtype: StatisticsWorkflows
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metrics(self) -> MapStringNumber:
        """Gets the metrics of this StatisticsWorkflows.


        :return: The metrics of this StatisticsWorkflows.
        :rtype: MapStringNumber
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics: MapStringNumber):
        """Sets the daily_runs of this StatisticsWorkflows.


        :param metrics: The metrics of this StatisticsWorkflows.
        :type metrics: MapStringNumber
        """

        self._metrics = metrics
