# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.map_string_number import MapStringNumber  # noqa: F401,E501
from swagger_server import util


class StatisticsRepositories(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stats: MapStringNumber=None):  # noqa: E501
        """StatisticsRepositories - a model defined in Swagger

        :param stats: The stats of this StatisticsRepositories.  # noqa: E501
        :type stats: MapStringNumber
        """
        self.swagger_types = {
            'stats': MapStringNumber
        }

        self.attribute_map = {
            'stats': 'stats'
        }
        self._stats = stats

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsRepositories':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_repositories of this StatisticsRepositories.  # noqa: E501
        :rtype: StatisticsRepositories
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stats(self) -> MapStringNumber:
        """Gets the stats of this StatisticsRepositories.


        :return: The stats of this StatisticsRepositories.
        :rtype: MapStringNumber
        """
        return self._stats

    @stats.setter
    def stats(self, stats: MapStringNumber):
        """Sets the stats of this StatisticsRepositories.


        :param stats: The stats of this StatisticsRepositories.
        :type stats: MapStringNumber
        """

        self._stats = stats
