# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.statistics_base import StatisticsBase  # noqa: F401,E501


class StatisticsPulls(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, merged: int = None, daily_closed_progress: Dict[str, int] = None,
                 daily_opened_progress: Dict[str, int] = None):  # noqa: E501
        """StatisticsPulls - a model defined in Swagger

        :param merged: The merged of this StatisticsPulls.  # noqa: E501
        :type merged: int
        :param daily_closed_progress: The daily_closed_progress of this StatisticsPulls.  # noqa: E501
        :type daily_closed_progress: Dict[str, int]
        :param daily_opened_progress: The daily_opened_progress of this StatisticsPulls.  # noqa: E501
        :type daily_opened_progress: Dict[str, int]
        """
        self.swagger_types = {
            'merged': int,
            'daily_closed_progress': Dict[str, int],
            'daily_opened_progress': Dict[str, int]
        }

        self.attribute_map = {
            'merged': 'merged',
            'daily_closed_progress': 'dailyClosedProgress',
            'daily_opened_progress': 'dailyOpenedProgress'
        }
        self._merged = merged
        self._daily_closed_progress = daily_closed_progress
        self._daily_opened_progress = daily_opened_progress

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsPulls':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_pulls of this StatisticsPulls.  # noqa: E501
        :rtype: StatisticsPulls
        """
        return util.deserialize_model(dikt, cls)

    @property
    def merged(self) -> int:
        """Gets the merged of this StatisticsPulls.


        :return: The merged of this StatisticsPulls.
        :rtype: int
        """
        return self._merged

    @merged.setter
    def merged(self, merged: int):
        """Sets the merged of this StatisticsPulls.


        :param merged: The merged of this StatisticsPulls.
        :type merged: int
        """

        self._merged = merged

    @property
    def daily_closed_progress(self) -> Dict[str, int]:
        """Gets the daily_closed_progress of this StatisticsPulls.


        :return: The daily_closed_progress of this StatisticsPulls.
        :rtype: Dict[str, int]
        """
        return self._daily_closed_progress

    @daily_closed_progress.setter
    def daily_closed_progress(self, daily_closed_progress: Dict[str, int]):
        """Sets the daily_closed_progress of this StatisticsPulls.


        :param daily_closed_progress: The daily_closed_progress of this StatisticsPulls.
        :type daily_closed_progress: Dict[str, int]
        """

        self._daily_closed_progress = daily_closed_progress

    @property
    def daily_opened_progress(self) -> Dict[str, int]:
        """Gets the daily_opened_progress of this StatisticsPulls.


        :return: The daily_opened_progress of this StatisticsPulls.
        :rtype: Dict[str, int]
        """
        return self._daily_opened_progress

    @daily_opened_progress.setter
    def daily_opened_progress(self, daily_opened_progress: Dict[str, int]):
        """Sets the daily_opened_progress of this StatisticsPulls.


        :param daily_opened_progress: The daily_opened_progress of this StatisticsPulls.
        :type daily_opened_progress: Dict[str, int]
        """

        self._daily_opened_progress = daily_opened_progress
