# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatisticsWorkflows(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metrics: Dict[str, int]=None):  # noqa: E501
        """StatisticsWorkflows - a model defined in Swagger

        :param metrics: The metrics of this StatisticsWorkflows.  # noqa: E501
        :type metrics: Dict[str, int]
        """
        self.swagger_types = {
            'metrics': Dict[str, int]
        }

        self.attribute_map = {
            'metrics': 'metrics'
        }
        self._metrics = metrics

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsWorkflows':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_workflows of this StatisticsWorkflows.  # noqa: E501
        :rtype: StatisticsWorkflows
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metrics(self) -> Dict[str, int]:
        """Gets the metrics of this StatisticsWorkflows.


        :return: The metrics of this StatisticsWorkflows.
        :rtype: Dict[str, int]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics: Dict[str, int]):
        """Sets the metrics of this StatisticsWorkflows.


        :param metrics: The metrics of this StatisticsWorkflows.
        :type metrics: Dict[str, int]
        """

        self._metrics = metrics
