# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Workflow(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, path: str=None, url: str=None, state: str=None, created_at: datetime=None, updated_at: datetime=None, file_url: str=None, size: str=None, lines: float=None):  # noqa: E501
        """Workflow - a model defined in Swagger

        :param id: The id of this Workflow.  # noqa: E501
        :type id: int
        :param name: The name of this Workflow.  # noqa: E501
        :type name: str
        :param path: The path of this Workflow.  # noqa: E501
        :type path: str
        :param url: The url of this Workflow.  # noqa: E501
        :type url: str
        :param state: The state of this Workflow.  # noqa: E501
        :type state: str
        :param created_at: The created_at of this Workflow.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Workflow.  # noqa: E501
        :type updated_at: datetime
        :param file_url: The file_url of this Workflow.  # noqa: E501
        :type file_url: str
        :param size: The size of this Workflow.  # noqa: E501
        :type size: str
        :param lines: The lines of this Workflow.  # noqa: E501
        :type lines: float
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'path': str,
            'url': str,
            'state': str,
            'created_at': datetime,
            'updated_at': datetime,
            'file_url': str,
            'size': str,
            'lines': float
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'path': 'path',
            'url': 'url',
            'state': 'state',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'file_url': 'file_url',
            'size': 'size',
            'lines': 'lines'
        }
        self._id = id
        self._name = name
        self._path = path
        self._url = url
        self._state = state
        self._created_at = created_at
        self._updated_at = updated_at
        self._file_url = file_url
        self._size = size
        self._lines = lines

    @classmethod
    def from_dict(cls, dikt) -> 'Workflow':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Workflow of this Workflow.  # noqa: E501
        :rtype: Workflow
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Workflow.


        :return: The id of this Workflow.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Workflow.


        :param id: The id of this Workflow.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Workflow.


        :return: The name of this Workflow.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Workflow.


        :param name: The name of this Workflow.
        :type name: str
        """

        self._name = name

    @property
    def path(self) -> str:
        """Gets the path of this Workflow.


        :return: The path of this Workflow.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this Workflow.


        :param path: The path of this Workflow.
        :type path: str
        """

        self._path = path

    @property
    def url(self) -> str:
        """Gets the url of this Workflow.


        :return: The url of this Workflow.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Workflow.


        :param url: The url of this Workflow.
        :type url: str
        """

        self._url = url

    @property
    def state(self) -> str:
        """Gets the state of this Workflow.


        :return: The state of this Workflow.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Workflow.


        :param state: The state of this Workflow.
        :type state: str
        """

        self._state = state

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Workflow.


        :return: The created_at of this Workflow.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Workflow.


        :param created_at: The created_at of this Workflow.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Workflow.


        :return: The updated_at of this Workflow.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Workflow.


        :param updated_at: The updated_at of this Workflow.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def file_url(self) -> str:
        """Gets the file_url of this Workflow.


        :return: The file_url of this Workflow.
        :rtype: str
        """
        return self._file_url

    @file_url.setter
    def file_url(self, file_url: str):
        """Sets the file_url of this Workflow.


        :param file_url: The file_url of this Workflow.
        :type file_url: str
        """

        self._file_url = file_url

    @property
    def size(self) -> str:
        """Gets the size of this Workflow.


        :return: The size of this Workflow.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this Workflow.


        :param size: The size of this Workflow.
        :type size: str
        """

        self._size = size

    @property
    def lines(self) -> float:
        """Gets the lines of this Workflow.


        :return: The lines of this Workflow.
        :rtype: float
        """
        return self._lines

    @lines.setter
    def lines(self, lines: float):
        """Sets the lines of this Workflow.


        :param lines: The lines of this Workflow.
        :type lines: float
        """

        self._lines = lines
