name: Generate Python SBOM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install CycloneDX tool
        run: pip install cyclonedx-bom

      # For requirements.txt projects
      - name: Generate SBOM from requirements.txt
        run: cyclonedx-py requirements requirements.txt -o sbom.json

      #Run license check script
      - name: Check Licenses
        run: python scripts/check_licenses.py

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.json