name: Pylint

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f test-requirements.txt ]; then
            pip install -r test-requirements.txt
          fi

      - name: Run insert_pylint_directives.py script
        run: python insert_pylint_directives.py

      - name: Static analysis the code with pylint
        run: |
          pylint --rcfile=.pylintrc swagger_server/ || pylint swagger_server/

