name: Pylint Tests

on:
  push:
    paths:
      - "swagger_server/test/**.py"
  pull_request:
    paths:
      - "swagger_server/test/**.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run insert_pylint_directives.py script
        run: python insert_pylint_directives.py

      - name: Analysing the code with pylint
        run: |
          FILES=$(git ls-files 'swagger_server/test/*.py')
          if [ -f .pylintrc ]; then
            pylint --rcfile=.pylintrc $FILES --output-format=text:lint.txt,colorized
          else
            pylint $FILES --output-format=text:lint.txt,colorized
          fi
          echo "Pylint completed"
          
      - name: Upload lint results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pylint-results-py${{ matrix.python-version }}
          path: lint.txt
